### ISSUE TITLE
fdisk: /dev/diskxxx: Resource busy

### ISSUE THREAD

**Issue by MattObject** [androindep/Bootchoice#2]
Have download source code and successfully built with Xcode 8.3.3 after hardcoding (WINDISK="/dev/disk0s3") our booting Windows partition. (It's the same on all lab machines).

Bootchoice launches, and does reboot when selecting Windows, but fails to boot Windows.

Bootchoice.log reports: 
fdisk: /dev/disk0s3: Resource busy
/Applications/Utilities/Bootchoice.app/Contents/Resources/setvals.sh: line 18: [: =: unary operator expected

**Comment by androindep** [comment]
Think there must be something unsupported about the point in setvals.sh at which you are hardcoding the variable, the script seem like it's trying to process that variable in the if statement that helps define what that variable becomes--you would want to remove the lines that deal with determining WINDISK and then hardcode your own. 

Of course, there is a supported method for manually determining the Windows boot partition that doesn't involve altering the source script:

Use the standard release version, but edit /Library/Preferences/bootchoice.plist
Set the PartitionAutoDetection key to FALSE and set the WindowsPartition key to /dev/disk0s3
