### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by hamburgerthemotionpicture** [androindep/Bootchoice#3]
Hi... I installed BootChoice, and it appears to be a quality piece of software, but it's not resolving the problem I am having.  I am migrating my Bootcamp partition from one hard drive to another, and I can't get the system to boot to the new hdd Window's partition. 

How do I go about uninstalling BootChoice?

Thanks,
hamburgerguy

**Comment by androindep** [comment]
I'm sorry it's not working out for you--I have yet to resolve issues with external/secondary drives. 

I probably should add a script in for uninstalling, but basically just delete these three files:
/Applications/Utilities/BootChoice.app
/Library/LaunchAgents/ca.ocadu.bootchoice.plist
/Library/Preferences/bootchoice.plist
